#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=check_gpu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:05:00
#SBATCH --output=jobs/logs/check_gpu_%A.log

module purge
module load 2024
module load Anaconda3/2024.06-1

# Go to your project root (where thesis_env lives)
cd $HOME/Thesis-LLM-CLD

# Activate your env by path
conda activate ./thesis_env

echo "===== System-level GPU info (nvidia-smi) ====="
nvidia-smi

echo "===== PyTorch-level GPU availability ====="
python -c "import torch; print('GPU available?', torch.cuda.is_available())"
