#!/bin/bash
#SBATCH -J llm_train
#SBATCH --partition=gpu_h100
#SBATCH --gres=gpu:2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=64G
#SBATCH --mail-user=gijs.schouten@student.uva.nl
#SBATCH --mail-type=ALL
#SBATCH --time=24:00:00
#SBATCH --array=1-30
#SBATCH -o jobs/logs/train_array_%A_%a.log

module purge
module load 2024
module load Anaconda3/2024.06-1

# ✱ REQUIRED to make `conda activate` work inside sbatch scripts
eval "$(conda shell.bash hook)"

cd $HOME/Thesis-LLM-CLD
conda activate ./thesis_env

# pass the array index into your python script
./thesis_env/bin/python src/train_array.py $SLURM_ARRAY_TASK_ID