#!/bin/bash

#SBATCH -J llm_train
#SBATCH --partition=gpu_h100
#SBATCH --gres=gpu:2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=64G
#SBATCH --time=24:00:00       # 24-hour wall clock—adjust as needed
#SBATCH -o jobs/logs/%Y/%m/%d/train_array_%j.log

module purge
module load 2024
module load Anaconda3/2024.06-1

# initialize conda in this shell
# eval "$(conda shell.bash hook)"

# load CUDA and Conda (if needed)
# module load cuda
cd $HOME/Thesis-LLM-CLD

# activate the env you created
conda activate ./thesis_env

# run the training script
./thesis_env/bin/python src/train_array.py %A_%a